tinkoff.session-id: ''
rest:
  tinkoff-terminal-api:
    url: https://api-invest.tinkoff.ru/trading
    app-name: "invest_terminal"
    app-version: "2.0.0"
  tinkoff-main-api:
    url: https://www.tinkoff.ru/api
  central-bank-rf-api:
    url: https://www.cbr.ru/scripts

spring:
  data:
    cassandra:
      keyspace-name: investment
      contact-points: 127.0.0.1:9042, 127.0.0.1:9043, 127.0.0.1:9044
      request:
        consistency: local_quorum
        throttler:
          max-queue-size: 3
          type: concurrency_limiting
          max-concurrent-requests: 3
      username: deal_calculator
      password: deal_calculator
      local-datacenter: Mars
logging.level:
  root: INFO
  ru.davydov.deal.calculator.service: INFO
