tinkoff.session-id: ''
rest:
  tinkoff-terminal-api:
    url: https://api-invest.tinkoff.ru/trading
    app-name: "invest_terminal"
    app-version: "2.0.0"
  tinkoff-main-api:
    url: https://www.tinkoff.ru/api
logging.level:
  root: INFO
  ru.davydov.deal.calculator.service.tinkoff: INFO
